/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Wiimote.xs. Do not edit this file, edit Wiimote.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Wiimote.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include <stdio.h>
#include <stdlib.h>
#include "wiimote.h"
#include "wiimote_api.h"

wiimote_t wiimote = WIIMOTE_INIT;

#line 22 "Wiimote.c"
XS(XS_Wiimote_c_wiimote_discover); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_wiimote_discover)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_wiimote_discover()");
    {
	char *	RETVAL;
	dXSTARG;
#line 16 "Wiimote.xs"
          wiimote_t wiimote[4];
          int nmotes = 0;
          int i = 0;
          nmotes = wiimote_discover(wiimote, 4);
          RETVAL = '  ';
          if ( nmotes > 0 ) {
             for (i=0; i<nmotes; i++) {
                RETVAL =  wiimote[i].link.r_addr;
             }
          } else {
             RETVAL = '0';
          }

#line 46 "Wiimote.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_wiimote_connect); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_wiimote_connect)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Wiimote::c_wiimote_connect(arg)");
    {
	int	RETVAL;
	dXSTARG;
	const char *	arg = (const char *)SvPV_nolen(ST(0));
#line 35 "Wiimote.xs"
          RETVAL = wiimote_connect(&wiimote, arg );
#line 64 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_is_open); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_is_open)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_is_open()");
    {
	int	RETVAL;
	dXSTARG;
#line 41 "Wiimote.xs"
          RETVAL = wiimote_is_open(&wiimote);
#line 81 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_wiimote_update); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_wiimote_update)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_wiimote_update()");
    {
	int	RETVAL;
	dXSTARG;
#line 47 "Wiimote.xs"
          RETVAL = wiimote_update(&wiimote);
#line 98 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_wiimote_disconnect); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_wiimote_disconnect)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_wiimote_disconnect()");
    {
	int	RETVAL;
	dXSTARG;
#line 53 "Wiimote.xs"
          RETVAL =  wiimote_disconnect(&wiimote);
#line 115 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_keys_raw_bits); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_keys_raw_bits)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_keys_raw_bits()");
    {
	int	RETVAL;
	dXSTARG;
#line 59 "Wiimote.xs"
          RETVAL =  wiimote.keys.bits;
#line 132 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_rumble); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_rumble)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_rumble()");
    {
	int	RETVAL;
	dXSTARG;
#line 65 "Wiimote.xs"
          RETVAL =  wiimote.rumble;
#line 149 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_set_wiimote_rumble); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_set_wiimote_rumble)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Wiimote::c_set_wiimote_rumble(arg)");
    {
	int	arg = (int)SvIV(ST(0));
#line 72 "Wiimote.xs"
          wiimote.rumble = arg;
#line 165 "Wiimote.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Wiimote_c_get_wiimote_ir); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_ir)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_ir()");
    {
	int	RETVAL;
	dXSTARG;
#line 76 "Wiimote.xs"
          RETVAL =  wiimote.mode.ir;
#line 181 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_set_wiimote_ir); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_set_wiimote_ir)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Wiimote::c_set_wiimote_ir(arg)");
    {
	int	arg = (int)SvIV(ST(0));
#line 83 "Wiimote.xs"
          wiimote.mode.ir = arg;
#line 197 "Wiimote.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Wiimote_c_get_wiimote_ext_nunchuk_joyx); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_ext_nunchuk_joyx)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_ext_nunchuk_joyx()");
    {
	int	RETVAL;
	dXSTARG;
#line 87 "Wiimote.xs"
          RETVAL =  wiimote.ext.nunchuk.joyx;
#line 213 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_ext_nunchuk_joyy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_ext_nunchuk_joyy)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_ext_nunchuk_joyy()");
    {
	int	RETVAL;
	dXSTARG;
#line 93 "Wiimote.xs"
          RETVAL =  wiimote.ext.nunchuk.joyy;
#line 230 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_ext_nunchuk_keys_c); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_ext_nunchuk_keys_c)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_ext_nunchuk_keys_c()");
    {
	int	RETVAL;
	dXSTARG;
#line 99 "Wiimote.xs"
          RETVAL =  wiimote.ext.nunchuk.keys.c;
#line 247 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_ext_nunchuk_keys_z); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_ext_nunchuk_keys_z)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_ext_nunchuk_keys_z()");
    {
	int	RETVAL;
	dXSTARG;
#line 105 "Wiimote.xs"
          RETVAL =  wiimote.ext.nunchuk.keys.z;
#line 264 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_ext_nunchuk_axis_x); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_ext_nunchuk_axis_x)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_ext_nunchuk_axis_x()");
    {
	int	RETVAL;
	dXSTARG;
#line 111 "Wiimote.xs"
          RETVAL =  wiimote.ext.nunchuk.axis.x;
#line 281 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_ext_nunchuk_axis_y); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_ext_nunchuk_axis_y)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_ext_nunchuk_axis_y()");
    {
	int	RETVAL;
	dXSTARG;
#line 117 "Wiimote.xs"
          RETVAL =  wiimote.ext.nunchuk.axis.y;
#line 298 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_ext_nunchuk_axis_z); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_ext_nunchuk_axis_z)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_ext_nunchuk_axis_z()");
    {
	int	RETVAL;
	dXSTARG;
#line 123 "Wiimote.xs"
          RETVAL =  wiimote.ext.nunchuk.axis.z;
#line 315 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_axis_x); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_axis_x)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_axis_x()");
    {
	int	RETVAL;
	dXSTARG;
#line 129 "Wiimote.xs"
          RETVAL =  wiimote.axis.x;
#line 332 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_axis_y); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_axis_y)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_axis_y()");
    {
	int	RETVAL;
	dXSTARG;
#line 135 "Wiimote.xs"
          RETVAL =  wiimote.axis.y;
#line 349 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_axis_z); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_axis_z)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_axis_z()");
    {
	int	RETVAL;
	dXSTARG;
#line 141 "Wiimote.xs"
          RETVAL =  wiimote.axis.z;
#line 366 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_tilt_x); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_tilt_x)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_tilt_x()");
    {
	float	RETVAL;
	dXSTARG;
#line 147 "Wiimote.xs"
          RETVAL =  wiimote.tilt.x;
#line 383 "Wiimote.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_tilt_y); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_tilt_y)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_tilt_y()");
    {
	float	RETVAL;
	dXSTARG;
#line 154 "Wiimote.xs"
          RETVAL =  wiimote.tilt.y;
#line 400 "Wiimote.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_tilt_z); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_tilt_z)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_tilt_z()");
    {
	float	RETVAL;
	dXSTARG;
#line 160 "Wiimote.xs"
          RETVAL =  wiimote.tilt.z;
#line 417 "Wiimote.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_activate_wiimote_accelerometer); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_activate_wiimote_accelerometer)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_activate_wiimote_accelerometer()");
    {
#line 166 "Wiimote.xs"
           wiimote.mode.acc = 1;
#line 432 "Wiimote.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Wiimote_c_deactivate_wiimote_accelerometer); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_deactivate_wiimote_accelerometer)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_deactivate_wiimote_accelerometer()");
    {
#line 170 "Wiimote.xs"
           wiimote.mode.acc = 0;
#line 446 "Wiimote.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Wiimote_c_get_wiimote_ir1_x); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_ir1_x)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_ir1_x()");
    {
	int	RETVAL;
	dXSTARG;
#line 174 "Wiimote.xs"
          RETVAL =  wiimote.ir1.x;
#line 462 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_ir1_y); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_ir1_y)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_ir1_y()");
    {
	int	RETVAL;
	dXSTARG;
#line 180 "Wiimote.xs"
          RETVAL =  wiimote.ir1.y;
#line 479 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_ir1_size); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_ir1_size)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_ir1_size()");
    {
	int	RETVAL;
	dXSTARG;
#line 186 "Wiimote.xs"
          RETVAL =  wiimote.ir1.size;
#line 496 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_ir2_x); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_ir2_x)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_ir2_x()");
    {
	int	RETVAL;
	dXSTARG;
#line 192 "Wiimote.xs"
          RETVAL =  wiimote.ir2.x;
#line 513 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_ir2_y); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_ir2_y)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_ir2_y()");
    {
	int	RETVAL;
	dXSTARG;
#line 198 "Wiimote.xs"
          RETVAL =  wiimote.ir2.y;
#line 530 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_ir2_size); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_ir2_size)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_ir2_size()");
    {
	int	RETVAL;
	dXSTARG;
#line 204 "Wiimote.xs"
          RETVAL =  wiimote.ir2.size;
#line 547 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_ir3_x); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_ir3_x)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_ir3_x()");
    {
	int	RETVAL;
	dXSTARG;
#line 210 "Wiimote.xs"
          RETVAL =  wiimote.ir3.x;
#line 564 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_ir3_y); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_ir3_y)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_ir3_y()");
    {
	int	RETVAL;
	dXSTARG;
#line 216 "Wiimote.xs"
          RETVAL =  wiimote.ir3.y;
#line 581 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_ir3_size); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_ir3_size)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_ir3_size()");
    {
	int	RETVAL;
	dXSTARG;
#line 222 "Wiimote.xs"
          RETVAL =  wiimote.ir3.size;
#line 598 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_ir4_x); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_ir4_x)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_ir4_x()");
    {
	int	RETVAL;
	dXSTARG;
#line 228 "Wiimote.xs"
          RETVAL =  wiimote.ir4.x;
#line 615 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_ir4_y); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_ir4_y)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_ir4_y()");
    {
	int	RETVAL;
	dXSTARG;
#line 234 "Wiimote.xs"
          RETVAL =  wiimote.ir4.y;
#line 632 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_ir4_size); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_ir4_size)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_ir4_size()");
    {
	int	RETVAL;
	dXSTARG;
#line 240 "Wiimote.xs"
          RETVAL =  wiimote.ir4.size;
#line 649 "Wiimote.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_force_x); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_force_x)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_force_x()");
    {
	float	RETVAL;
	dXSTARG;
#line 246 "Wiimote.xs"
          RETVAL =  wiimote.force.x;
#line 666 "Wiimote.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_force_y); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_force_y)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_force_y()");
    {
	float	RETVAL;
	dXSTARG;
#line 252 "Wiimote.xs"
          RETVAL =  wiimote.force.y;
#line 683 "Wiimote.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Wiimote_c_get_wiimote_force_z); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wiimote_c_get_wiimote_force_z)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Wiimote::c_get_wiimote_force_z()");
    {
	float	RETVAL;
	dXSTARG;
#line 258 "Wiimote.xs"
          RETVAL =  wiimote.force.z;
#line 700 "Wiimote.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Wiimote); /* prototype to pass -Wmissing-prototypes */
XS(boot_Wiimote)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("Wiimote::c_wiimote_discover", XS_Wiimote_c_wiimote_discover, file);
        newXS("Wiimote::c_wiimote_connect", XS_Wiimote_c_wiimote_connect, file);
        newXS("Wiimote::c_is_open", XS_Wiimote_c_is_open, file);
        newXS("Wiimote::c_wiimote_update", XS_Wiimote_c_wiimote_update, file);
        newXS("Wiimote::c_wiimote_disconnect", XS_Wiimote_c_wiimote_disconnect, file);
        newXS("Wiimote::c_get_wiimote_keys_raw_bits", XS_Wiimote_c_get_wiimote_keys_raw_bits, file);
        newXS("Wiimote::c_get_wiimote_rumble", XS_Wiimote_c_get_wiimote_rumble, file);
        newXS("Wiimote::c_set_wiimote_rumble", XS_Wiimote_c_set_wiimote_rumble, file);
        newXS("Wiimote::c_get_wiimote_ir", XS_Wiimote_c_get_wiimote_ir, file);
        newXS("Wiimote::c_set_wiimote_ir", XS_Wiimote_c_set_wiimote_ir, file);
        newXS("Wiimote::c_get_wiimote_ext_nunchuk_joyx", XS_Wiimote_c_get_wiimote_ext_nunchuk_joyx, file);
        newXS("Wiimote::c_get_wiimote_ext_nunchuk_joyy", XS_Wiimote_c_get_wiimote_ext_nunchuk_joyy, file);
        newXS("Wiimote::c_get_wiimote_ext_nunchuk_keys_c", XS_Wiimote_c_get_wiimote_ext_nunchuk_keys_c, file);
        newXS("Wiimote::c_get_wiimote_ext_nunchuk_keys_z", XS_Wiimote_c_get_wiimote_ext_nunchuk_keys_z, file);
        newXS("Wiimote::c_get_wiimote_ext_nunchuk_axis_x", XS_Wiimote_c_get_wiimote_ext_nunchuk_axis_x, file);
        newXS("Wiimote::c_get_wiimote_ext_nunchuk_axis_y", XS_Wiimote_c_get_wiimote_ext_nunchuk_axis_y, file);
        newXS("Wiimote::c_get_wiimote_ext_nunchuk_axis_z", XS_Wiimote_c_get_wiimote_ext_nunchuk_axis_z, file);
        newXS("Wiimote::c_get_wiimote_axis_x", XS_Wiimote_c_get_wiimote_axis_x, file);
        newXS("Wiimote::c_get_wiimote_axis_y", XS_Wiimote_c_get_wiimote_axis_y, file);
        newXS("Wiimote::c_get_wiimote_axis_z", XS_Wiimote_c_get_wiimote_axis_z, file);
        newXS("Wiimote::c_get_wiimote_tilt_x", XS_Wiimote_c_get_wiimote_tilt_x, file);
        newXS("Wiimote::c_get_wiimote_tilt_y", XS_Wiimote_c_get_wiimote_tilt_y, file);
        newXS("Wiimote::c_get_wiimote_tilt_z", XS_Wiimote_c_get_wiimote_tilt_z, file);
        newXS("Wiimote::c_activate_wiimote_accelerometer", XS_Wiimote_c_activate_wiimote_accelerometer, file);
        newXS("Wiimote::c_deactivate_wiimote_accelerometer", XS_Wiimote_c_deactivate_wiimote_accelerometer, file);
        newXS("Wiimote::c_get_wiimote_ir1_x", XS_Wiimote_c_get_wiimote_ir1_x, file);
        newXS("Wiimote::c_get_wiimote_ir1_y", XS_Wiimote_c_get_wiimote_ir1_y, file);
        newXS("Wiimote::c_get_wiimote_ir1_size", XS_Wiimote_c_get_wiimote_ir1_size, file);
        newXS("Wiimote::c_get_wiimote_ir2_x", XS_Wiimote_c_get_wiimote_ir2_x, file);
        newXS("Wiimote::c_get_wiimote_ir2_y", XS_Wiimote_c_get_wiimote_ir2_y, file);
        newXS("Wiimote::c_get_wiimote_ir2_size", XS_Wiimote_c_get_wiimote_ir2_size, file);
        newXS("Wiimote::c_get_wiimote_ir3_x", XS_Wiimote_c_get_wiimote_ir3_x, file);
        newXS("Wiimote::c_get_wiimote_ir3_y", XS_Wiimote_c_get_wiimote_ir3_y, file);
        newXS("Wiimote::c_get_wiimote_ir3_size", XS_Wiimote_c_get_wiimote_ir3_size, file);
        newXS("Wiimote::c_get_wiimote_ir4_x", XS_Wiimote_c_get_wiimote_ir4_x, file);
        newXS("Wiimote::c_get_wiimote_ir4_y", XS_Wiimote_c_get_wiimote_ir4_y, file);
        newXS("Wiimote::c_get_wiimote_ir4_size", XS_Wiimote_c_get_wiimote_ir4_size, file);
        newXS("Wiimote::c_get_wiimote_force_x", XS_Wiimote_c_get_wiimote_force_x, file);
        newXS("Wiimote::c_get_wiimote_force_y", XS_Wiimote_c_get_wiimote_force_y, file);
        newXS("Wiimote::c_get_wiimote_force_z", XS_Wiimote_c_get_wiimote_force_z, file);
    XSRETURN_YES;
}

